// Generated by docs/palette_check.py --swift. Do not edit by hand.
//
// The ramp and its contrast floors are defined and verified in that script,
// which CI runs. Editing a value here would pass the build and silently break
// the guarantee that every numeral clears 4.5:1 on its own card.

import SwiftUI

/// Colours for the thirteen card values.
///
/// Hue belongs to values. States are expressed with luminance, saturation and
/// motion, never a new hue on a card, because thirteen values already consume
/// nearly the whole wheel.
enum CardPalette {
  /// The card surface. Low chroma; this is the resting state.
  static func wash(for value: Int) -> Color { dynamic(washes, value) }

  /// The numeral. Solved to at least 4.5:1 against its own wash in both modes.
  static func ink(for value: Int) -> Color { dynamic(inks, value) }

  /// Full chroma. The Rail, and the card edge at 35%.
  static func rail(for value: Int) -> Color { dynamic(rails, value) }

  private static func dynamic(_ ramp: [(light: UInt32, dark: UInt32)], _ value: Int) -> Color {
    let pair = ramp[min(max(value, 0), ramp.count - 1)]
    return Color(
      UIColor { traits in
        UIColor(rgb: traits.userInterfaceStyle == .dark ? pair.dark : pair.light)
      })
  }

  private static let washes: [(light: UInt32, dark: UInt32)] = [
    (light: 0xDBDBDB, dark: 0x424242),
    (light: 0xF5C8C2, dark: 0x67281E),
    (light: 0xF5D8C2, dark: 0x673D1E),
    (light: 0xF5E6C2, dark: 0x67511E),
    (light: 0xF5F1C2, dark: 0x67611E),
    (light: 0xE6F5C2, dark: 0x51671E),
    (light: 0xCEF5C2, dark: 0x30671E),
    (light: 0xC2F5D4, dark: 0x1E6739),
    (light: 0xC2F5EB, dark: 0x1E6758),
    (light: 0xC2EBF5, dark: 0x1E5867),
    (light: 0xCCC2F5, dark: 0x2C1E67),
    (light: 0xE2C2F5, dark: 0x4C1E67),
    (light: 0xF5C2EB, dark: 0x671E58),
  ]

  private static let inks: [(light: UInt32, dark: UInt32)] = [
    (light: 0x5E5E5E, dark: 0xB0B0B0),
    (light: 0xAF240E, dark: 0xF88877),
    (light: 0x9C4B0D, dark: 0xF7A15F),
    (light: 0x84600B, dark: 0xF5C147),
    (light: 0x766D0A, dark: 0xF3E220),
    (light: 0x55760A, dark: 0xB4F320),
    (light: 0x25760A, dark: 0x55F320),
    (light: 0x0A7631, dark: 0x20F36E),
    (light: 0x0A7660, dark: 0x20F3C9),
    (light: 0x0B6C84, dark: 0x4CD4F6),
    (light: 0x3912D9, dark: 0x9981F8),
    (light: 0x8310C6, dark: 0xCB7CF8),
    (light: 0xA50D87, dark: 0xF877DE),
  ]

  private static let rails: [(light: UInt32, dark: UInt32)] = [
    (light: 0x7A7A7A, dark: 0x858585),
    (light: 0xD33A22, dark: 0xE04129),
    (light: 0xD36F22, dark: 0xE07829),
    (light: 0xAF831D, dark: 0xE0A929),
    (light: 0x958B18, dark: 0xE0D129),
    (light: 0x709518, dark: 0xA9E029),
    (light: 0x3B9E1A, dark: 0x57E029),
    (light: 0x1A9E4A, dark: 0x29E06C),
    (light: 0x1A9E83, dark: 0x29E0BC),
    (light: 0x1D96B4, dark: 0x29BCE0),
    (light: 0x4622D3, dark: 0x5936E2),
    (light: 0x9222D3, dark: 0x9D29E0),
    (light: 0xD322AF, dark: 0xE029BC),
  ]
}

extension UIColor {
  fileprivate convenience init(rgb: UInt32) {
    self.init(
      red: CGFloat((rgb >> 16) & 0xFF) / 255,
      green: CGFloat((rgb >> 8) & 0xFF) / 255,
      blue: CGFloat(rgb & 0xFF) / 255,
      alpha: 1
    )
  }
}

/// Table and surface tokens.
///
/// The table is true black in dark mode, not a lifted grey: tinted cards pop
/// hardest on black, and on OLED it is a real energy saving.
enum TablePalette {
  static let table = Color(
    UIColor { $0.userInterfaceStyle == .dark ? .black : .systemGroupedBackground })
  static let surface = Color(.secondarySystemGroupedBackground)
}
